name: flutter_xboard_sdk
description: "XBoard网站的Flutter SDK，提供认证、订阅管理等功能"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  http: ^1.4.0
  html: ^0.15.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  dio: ^5.5.0+1
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.24.9