name: flutter_xboard_sdk
description: "XBoard网站的Flutter SDK，提供认证、订阅管理等功能"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1

  html: ^0.15.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.24.9

flutter:
  assets:
    - assets/cer/